#!/bin/env python

import requests
import argparse

IMDB = "http://www.omdbapi.com/"

parser = argparse.ArgumentParser(description='Get movie genre')
parser.add_argument('TITLE', help='Specify title of movie/show')

args = parser.parse_args()

r = requests.get(IMDB + "?t=" + args.TITLE)
print r.json()['Genre']
